In [11]:
import pandas as pd
data = pd.read_csv(r'C:\Users\user\OneDrive\VS CODE\PANDAS\world_population_by_country_2026.csv', index_col = 0)
print(data)

               Country  Population_2026  Yearly_Change  Net_Change  \
Rank
1                India       1476625576           0.87  12760051.0
2                China       1412914089          -0.22  -3182005.0
3        United States        349035494           0.51   1759687.0
4            Indonesia        287886782           0.76   2165546.0
5             Pakistan        259299791           1.60   4080237.0
...                ...              ...            ...         ...
229         Montserrat             4328          -0.71       -31.0
230   Falkland Islands             3465          -0.12        -4.0
231            Tokelau             2691           3.18        83.0
232               Niue             1822           0.05         1.0
233           Holy See              506           1.00         5.0

      Density_per_km2  Land_Area_km2  Migrants_Net  Fertility_Rate  \
Rank
1                 497        2973190     -440456.0            1.93
2                 150        9388211     -232107.0            1.03
3                  38        9147420     1177848.0            1.63
4                 159        1811570      -39472.0            2.08
5                 336         770880    -1144738.0            3.44
...               ...            ...           ...             ...
229                43            100         -10.0            1.45
230                 0          12170         -16.0            1.69
231               269             10          43.0            2.54
232                 7            260           2.0            2.44
233              1265              0          13.0            1.00

      Median_Age  Urban_Population_pct  World_Share_pct
Rank
1           29.2                  37.6        17.790000
2           40.6                  68.7        17.020000
3           38.7                  83.1         4.200000
4           30.7                  60.3         3.470000
5           20.8                  34.7         3.120000
...          ...                   ...              ...
229         41.8                  11.7         0.000052
230         43.4                  68.4         0.000042
231         27.6                   0.0         0.000032
232         35.1                  45.2         0.000022
233         56.2                   0.0         0.000006

[233 rows x 11 columns]

In [12]:
print(data['Population_2026'] > 1000000000)

Rank
1       True
2       True
3      False
4      False
5      False
       ...
229    False
230    False
231    False
232    False
233    False
Name: Population_2026, Length: 233, dtype: bool

In [33]:
is_huge = data['Population_2026'] > 190000000
data[is_huge]

,Country,Population_2026,Yearly_Change,Net_Change,Density_per_km2,Land_Area_km2,Migrants_Net,Fertility_Rate,Median_Age,Urban_Population_pct,World_Share_pct
Rank,,,,,,,,,,,
1,India,1476625576,0.87,12760051.0,497,2973190,-440456.0,1.93,29.2,37.6,17.79
2,China,1412914089,-0.22,-3182005.0,150,9388211,-232107.0,1.03,40.6,68.7,17.02
3,United States,349035494,0.51,1759687.0,38,9147420,1177848.0,1.63,38.7,83.1,4.20
4,Indonesia,287886782,0.76,2165546.0,159,1811570,-39472.0,2.08,30.7,60.3,3.47
5,Pakistan,259299791,1.60,4080237.0,336,770880,-1144738.0,3.44,20.8,34.7,3.12
6,Nigeria,242431832,2.06,4904050.0,266,910770,-2810.0,4.21,18.3,55.8,2.92
7,Brazil,213562666,0.35,750261.0,26,8358140,-205642.0,1.59,35.3,91.7,2.57

In [34]:
data[data['Population_2026']>190000000]

,Country,Population_2026,Yearly_Change,Net_Change,Density_per_km2,Land_Area_km2,Migrants_Net,Fertility_Rate,Median_Age,Urban_Population_pct,World_Share_pct
Rank,,,,,,,,,,,
1,India,1476625576,0.87,12760051.0,497,2973190,-440456.0,1.93,29.2,37.6,17.79
2,China,1412914089,-0.22,-3182005.0,150,9388211,-232107.0,1.03,40.6,68.7,17.02
3,United States,349035494,0.51,1759687.0,38,9147420,1177848.0,1.63,38.7,83.1,4.20
4,Indonesia,287886782,0.76,2165546.0,159,1811570,-39472.0,2.08,30.7,60.3,3.47
5,Pakistan,259299791,1.60,4080237.0,336,770880,-1144738.0,3.44,20.8,34.7,3.12
6,Nigeria,242431832,2.06,4904050.0,266,910770,-2810.0,4.21,18.3,55.8,2.92
7,Brazil,213562666,0.35,750261.0,26,8358140,-205642.0,1.59,35.3,91.7,2.57